//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package server

import (
	common "k8s.io/kube-openapi/pkg/common"
	spec "k8s.io/kube-openapi/pkg/validation/spec"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.Analytics":                    schema_loft_sh_admin_services_pkg_server_Analytics(ref),
		"github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.Button":                       schema_loft_sh_admin_services_pkg_server_Button(ref),
		"github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.InstanceTokenAuth":            schema_loft_sh_admin_services_pkg_server_InstanceTokenAuth(ref),
		"github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.License":                      schema_loft_sh_admin_services_pkg_server_License(ref),
		"github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.Request":                      schema_loft_sh_admin_services_pkg_server_Request(ref),
		"github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.ResourceQuantity":             schema_loft_sh_admin_services_pkg_server_ResourceQuantity(ref),
		"github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.StandardRequestInput":         schema_loft_sh_admin_services_pkg_server_StandardRequestInput(ref),
		"github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.StandardRequestInputFrontEnd": schema_loft_sh_admin_services_pkg_server_StandardRequestInputFrontEnd(ref),
		"github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.StandardRequestOutput":        schema_loft_sh_admin_services_pkg_server_StandardRequestOutput(ref),
	}
}

func schema_loft_sh_admin_services_pkg_server_Analytics(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Analytics is a struct that represents the analytics server and the requests that should be sent to it. This information is sent to Loft instances when they check in with the license server.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"endpoint": {
						SchemaProps: spec.SchemaProps{
							Description: "Endpoint is the endpoint for the analytics server.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"requests": {
						SchemaProps: spec.SchemaProps{
							Description: "Requests is a slice of requested resources to return analytics for.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.Request"),
									},
								},
							},
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.Request"},
	}
}

func schema_loft_sh_admin_services_pkg_server_Button(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Button is an object that represents a button in the Loft UI that links to some external service for handling operations for licensing for example.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"URL": {
						SchemaProps: spec.SchemaProps{
							Description: "URL is the link at the other end of the button.",
							Default:     "",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"displayText": {
						SchemaProps: spec.SchemaProps{
							Description: "DisplayText is the text to display on the button. If display text is unset the button will never be shown in the loft UI.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"payloadType": {
						SchemaProps: spec.SchemaProps{
							Description: "PayloadType indicates the payload type to set in the request. Typically, this will be \"standard\" -- meaning the standard payload that includes the instance token auth and a return url, however in the future we may add additional types. An unset value is assumed to be \"standard\".",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"direct": {
						SchemaProps: spec.SchemaProps{
							Description: "Direct indicates if the Loft front end should directly hit this endpoint. If false, it means that the Loft front end will be hitting the license server first to generate a one time token for the operation; this also means that there will be a redirect URL in the response to the request for this and that link should be followed by the front end.",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
				},
				Required: []string{"URL"},
			},
		},
	}
}

func schema_loft_sh_admin_services_pkg_server_InstanceTokenAuth(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"token": {
						SchemaProps: spec.SchemaProps{
							Description: "Token is the jwt token identifying the loft instance.",
							Default:     "",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"certificate": {
						SchemaProps: spec.SchemaProps{
							Description: "Certificate is the signing certificate for the token.",
							Default:     "",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"token", "certificate"},
			},
		},
	}
}

func schema_loft_sh_admin_services_pkg_server_License(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "License is a struct representing the license data sent to a Loft instance after checking in with the license server.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"buttons": {
						SchemaProps: spec.SchemaProps{
							Description: "Buttons is a slice of license server endpoints (buttons) that the Loft instance may need to hit. Each Button contains the display text and link for the front end to work with.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.Button"),
									},
								},
							},
						},
					},
					"isOffline": {
						SchemaProps: spec.SchemaProps{
							Description: "IsOffline indicates if the license is an offline license or not.",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"announcement": {
						SchemaProps: spec.SchemaProps{
							Description: "Announcements is a map string/string such that we can easily add any additional data without needing to change types. For now, we will use the keys \"name\" and \"content\".",
							Type:        []string{"object"},
							AdditionalProperties: &spec.SchemaOrBool{
								Allows: true,
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: "",
										Type:    []string{"string"},
										Format:  "",
									},
								},
							},
						},
					},
					"blockRequests": {
						SchemaProps: spec.SchemaProps{
							Description: "BlockRequests is a slice of Request objects that the Loft instance should block from being created due to license usage overrun.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.Request"),
									},
								},
							},
						},
					},
					"limits": {
						SchemaProps: spec.SchemaProps{
							Description: "Limits is the number of resources allowed by the current license.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.ResourceQuantity"),
									},
								},
							},
						},
					},
					"features": {
						SchemaProps: spec.SchemaProps{
							Description: "Features is a map of enabled features.",
							Type:        []string{"object"},
							AdditionalProperties: &spec.SchemaOrBool{
								Allows: true,
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: false,
										Type:    []string{"boolean"},
										Format:  "",
									},
								},
							},
						},
					},
					"analytics": {
						SchemaProps: spec.SchemaProps{
							Description: "Analytics indicates the analytics endpoints and which requests should be sent to the analytics server.",
							Ref:         ref("github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.Analytics"),
						},
					},
					"domainToken": {
						SchemaProps: spec.SchemaProps{
							Description: "DomainToken holds the JWT with the URL that the Loft instance is publicly available on. (via Loft router)",
							Default:     "",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.Analytics", "github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.Button", "github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.Request", "github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.ResourceQuantity"},
	}
}

func schema_loft_sh_admin_services_pkg_server_Request(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Request represents a request analytics information for an apigroup/resource and a list of verb actions for that resource.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"verbs": {
						SchemaProps: spec.SchemaProps{
							Description: "Verbs is the list of verbs for the request.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: "",
										Type:    []string{"string"},
										Format:  "",
									},
								},
							},
						},
					},
					"group": {
						SchemaProps: spec.SchemaProps{
							Description: "Group is the api group.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"resource": {
						SchemaProps: spec.SchemaProps{
							Description: "Resource is the resource name for the request.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
			},
		},
	}
}

func schema_loft_sh_admin_services_pkg_server_ResourceQuantity(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ResourceQuantity represents an api resource and a quantity counter for that resource type (used for limits for example).",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"group": {
						SchemaProps: spec.SchemaProps{
							Description: "Group is the api group.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"version": {
						SchemaProps: spec.SchemaProps{
							Description: "Version is the api version.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is the resource kind.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"quantity": {
						SchemaProps: spec.SchemaProps{
							Description: "Quantity is the quantity for hte limit (for example).",
							Default:     0,
							Type:        []string{"integer"},
							Format:      "int64",
						},
					},
				},
				Required: []string{"quantity"},
			},
		},
	}
}

func schema_loft_sh_admin_services_pkg_server_StandardRequestInput(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "StandardRequestInput is a standard payload object used between the Loft front end and the Loft admin server. It accepts auth information and a URL that is used by the admin server when crafting the redirect link that is returned from \"start\" type operations (ex. trial activate start that creates a one-time token and returns a url to go to for the front end).",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"InstanceTokenAuth": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.InstanceTokenAuth"),
						},
					},
					"StandardRequestInputFrontEnd": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.StandardRequestInputFrontEnd"),
						},
					},
				},
				Required: []string{"InstanceTokenAuth", "StandardRequestInputFrontEnd"},
			},
		},
		Dependencies: []string{
			"github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.InstanceTokenAuth", "github.com/loft-sh/external-types/loft-sh/admin-services/pkg/server.StandardRequestInputFrontEnd"},
	}
}

func schema_loft_sh_admin_services_pkg_server_StandardRequestInputFrontEnd(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "StandardRequestInputFrontEnd is the standard input request payload for the front end -- this is the same (it is embedded) in the StandardRequestInput just without the token auth as the Loft backend will handle adding that for communication to the admin server.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"returnURL": {
						SchemaProps: spec.SchemaProps{
							Description: "ReturnURL is the url that operations should ultimately return to after their operation is complete. For example, once the license activate process is done, the Loft portal should redirect to this URL.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
			},
		},
	}
}

func schema_loft_sh_admin_services_pkg_server_StandardRequestOutput(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "StandardRequestOutput is a standard payload object returned by the Loft admin server, it contains a RedirectURL that encodes a one-time token (if applicable) and a return URL (if applicable) that the front end can then follow to continue the license operation.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"redirectURL": {
						SchemaProps: spec.SchemaProps{
							Description: "RedirectURL is the URL to redirect to for continuing the license operation (typically stripe or the loft portal).",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
			},
		},
	}
}
